version: "3.5"
services:
  database_master:
    image: mysql:8.0.30
    container_name: "dev-go"
    restart: always
    ports:
      - 3300:3306
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_USER=aplicacao
      - MYSQL_DATABASE=dev
      - MYSQL_PASSWORD=1212